// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProject(arg1) {
  return window['go']['main']['App']['CreateNewProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetDatabaseList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDatabaseList'](arg1, arg2, arg3, arg4);
}

export function GetProjectEnv(arg1) {
  return window['go']['main']['App']['GetProjectEnv'](arg1);
}

export function GetTableList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTableList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTableSchema(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function SaveProjectEnv(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectEnv'](arg1, arg2);
}
